---
- name: Create, Update and Delete Credentials
  dilerous.powerprotect.credential:
    name: "{{ item.name }}"
    username: "{{ item.policy_name | default(item.name) }}"
    cred_type: "{{ item.cred_type | default(cred_type) }}"
    password: "{{ item.password }}"
    method: "{{ item.method | default(method) }}"
    token: "{{ ansible_facts['access_token'] }}"
    server: "{{ inventory_hostname }}"
  loop: "{{ credentials }}"
  loop_control:
    label: "Rule: {{ item.name }} | State: {{ item.state }}"
