---
# tasks file for protection_rule
- name: run the new module
  dilerous.powerprotect.protection_rule:
    server: "{{ inventory_hostname }}"
    password: "{{ password }}"
    name: "{{ item.name }}"
    policy_name: "{{ item.policy_name }}"
    inventory_type: "{{ item.inventory_type | default('KUBERNETES') }}"
    label: "{{ item.label }}"
  loop: "{{ protection_rules }}"
