- name: Create Protection Rules
  hosts: localhost
  vars_files:
  - ./vars.yml
  tasks:
  - name: run the new module
    protection_rule:

      rule_name: 'newprotrule'
      policy_name: 'hourly'
      inventory_type: 'KUBERNETES'
      label: 'backup=foreverly'
  - name: run the new 2nd module
    protection_rule:
      rule_name: '2ndnewprotrule'
      policy_name: 'hourly'
      inventory_type: 'KUBERNETES'
      label: 'backup=thirdlsyadfsjkl'
